routes/web.php
    Route::get('/contracts/bitrix/create', 'BitrixContractController@create')->name('contracts.bitrix.create');
    Route::post('/contracts/bitrix/store', 'BitrixContractController@store')->name('contracts.bitrix.store');
    Route::get('/contracts/bitrix/{contract}/edit', 'BitrixContractController@edit')->name('contracts.bitrix.edit');
    Route::put('/contracts/bitrix/{contract}', 'BitrixContractController@update')->name('contracts.bitrix.update');
    Route::get('/contracts/bitrix/{contract}', 'BitrixContractController@show')->name('contracts.bitrix.show');
    Route::delete('/contracts/bitrix/{contract}', 'BitrixContractController@destroy')->name('contracts.bitrix.destroy');
    Route::delete('/contracts/bitrix/{contract}/force-delete', 'BitrixContractController@forceDelete')->name('contracts.bitrix.force-delete');
    Route::get('/contracts/bitrix/{contract}/restore', 'BitrixContractController@restore')->name('contracts.bitrix.restore');
    Route::get('/contracts/bitrix/{contract}/download', 'BitrixContractController@download')->name('contracts.bitrix.download');
    Route::post('/contracts/bitrix/{contract}/decline', 'BitrixContractController@decline')->name('contracts.bitrix.decline');
    Route::get('/contracts/bitrix/{contract}/activate', 'BitrixContractController@activate')->name('contracts.bitrix.activate');
    Route::post('/contracts/bitrix/{contract}/renew', 'BitrixContractController@renew')->name('contracts.bitrix.renew');
    Route::get('/contracts/bitrix/{contract}/download-file/{file}', 'BitrixContractController@downloadFile')->name('contracts.bitrix.download-file');
    Route::get('/contracts/bitrix/{contract}/delete-file/{file}', 'BitrixContractController@deleteFile')->name('contracts.bitrix.delete-file');
    Route::get('/contracts/bitrix/{contract}/download-cancellation-letter', 'BitrixContractController@downloadCancellationLetter')->name('contracts.bitrix.download-cancellation-letter');
    Route::get('/contracts/bitrix/{contract}/download-cancellation-agreement', 'BitrixContractController@downloadCancellationAgreement')->name('contracts.bitrix.download-cancellation-agreement');

    Route::get('/contracts/bitrix-crm/{status?}', 'BitrixCRMContractController@index')->where('status', 'active|declined|deleted')->name('contracts.bitrix-crm.index');
    Route::get('/contracts/bitrix-crm/create', 'BitrixCRMContractController@create')->name('contracts.bitrix-crm.create');
    Route::post('/contracts/bitrix-crm/store', 'BitrixCRMContractController@store')->name('contracts.bitrix-crm.store');
    Route::get('/contracts/bitrix-crm/{contract}/edit', 'BitrixCRMContractController@edit')->name('contracts.bitrix-crm.edit');
    Route::put('/contracts/bitrix-crm/{contract}', 'BitrixCRMContractController@update')->name('contracts.bitrix-crm.update');
    Route::get('/contracts/bitrix-crm/{contract}', 'BitrixCRMContractController@show')->name('contracts.bitrix-crm.show');
    Route::delete('/contracts/bitrix-crm/{contract}', 'BitrixCRMContractController@destroy')->name('contracts.bitrix-crm.destroy');
    Route::delete('/contracts/bitrix-crm/{contract}/force-delete', 'BitrixCRMContractController@forceDelete')->name('contracts.bitrix-crm.force-delete');
    Route::get('/contracts/bitrix-crm/{contract}/restore', 'BitrixCRMContractController@restore')->name('contracts.bitrix-crm.restore');
    Route::get('/contracts/bitrix-crm/{contract}/download', 'BitrixCRMContractController@download')->name('contracts.bitrix-crm.download');
    Route::post('/contracts/bitrix-crm/{contract}/decline', 'BitrixCRMContractController@decline')->name('contracts.bitrix-crm.decline');
    Route::get('/contracts/bitrix-crm/{contract}/activate', 'BitrixCRMContractController@activate')->name('contracts.bitrix-crm.activate');
    Route::post('/contracts/bitrix-crm/{contract}/renew', 'BitrixCRMContractController@renew')->name('contracts.bitrix-crm.renew');
    Route::get('/contracts/bitrix-crm/{contract}/download-file/{file}', 'BitrixCRMContractController@downloadFile')->name('contracts.bitrix-crm.download-file');
    Route::get('/contracts/bitrix-crm/{contract}/delete-file/{file}', 'BitrixCRMContractController@deleteFile')->name('contracts.bitrix-crm.delete-file');
    Route::get('/contracts/bitrix-crm/{contract}/download-cancellation-letter', 'BitrixCRMContractController@downloadCancellationLetter')->name('contracts.bitrix-crm.download-cancellation-letter');
    Route::get('/contracts/bitrix-crm/{contract}/download-cancellation-agreement', 'BitrixCRMContractController@downloadCancellationAgreement')->name('contracts.bitrix-crm.download-cancellation-agreement');

    Route::get('/contracts/amo-crm/{status?}', 'AmoCRMContractController@index')->where('status', 'active|declined|deleted')->name('contracts.amo-crm.index');
    Route::get('/contracts/amo-crm/create', 'AmoCRMContractController@create')->name('contracts.amo-crm.create');
    Route::post('/contracts/amo-crm/store', 'AmoCRMContractController@store')->name('contracts.amo-crm.store');
    Route::get('/contracts/amo-crm/{contract}/edit', 'AmoCRMContractController@edit')->name('contracts.amo-crm.edit');
    Route::put('/contracts/amo-crm/{contract}', 'AmoCRMContractController@update')->name('contracts.amo-crm.update');
    Route::get('/contracts/amo-crm/{contract}', 'AmoCRMContractController@show')->name('contracts.amo-crm.show');
    Route::delete('/contracts/amo-crm/{contract}', 'AmoCRMContractController@destroy')->name('contracts.amo-crm.destroy');
    Route::delete('/contracts/amo-crm/{contract}/force-delete', 'AmoCRMContractController@forceDelete')->name('contracts.amo-crm.force-delete');
    Route::get('/contracts/amo-crm/{contract}/restore', 'AmoCRMContractController@restore')->name('contracts.amo-crm.restore');
    Route::get('/contracts/amo-crm/{contract}/download', 'AmoCRMContractController@download')->name('contracts.amo-crm.download');
    Route::post('/contracts/amo-crm/{contract}/decline', 'AmoCRMContractController@decline')->name('contracts.amo-crm.decline');
    Route::get('/contracts/amo-crm/{contract}/activate', 'AmoCRMContractController@activate')->name('contracts.amo-crm.activate');
    Route::post('/contracts/amo-crm/{contract}/renew', 'AmoCRMContractController@renew')->name('contracts.amo-crm.renew');
    Route::get('/contracts/amo-crm/{contract}/download-file/{file}', 'AmoCRMContractController@downloadFile')->name('contracts.amo-crm.download-file');
    Route::get('/contracts/amo-crm/{contract}/delete-file/{file}', 'AmoCRMContractController@deleteFile')->name('contracts.amo-crm.delete-file');
    Route::get('/contracts/amo-crm/{contract}/download-cancellation-letter', 'AmoCRMContractController@downloadCancellationLetter')->name('contracts.amo-crm.download-cancellation-letter');
    Route::get('/contracts/amo-crm/{contract}/download-cancellation-agreement', 'AmoCRMContractController@downloadCancellationAgreement')->name('contracts.amo-crm.download-cancellation-agreement');
    
    Route::resource('/permissions', 'PermissionController', ['except' => ['destroy', 'show']]);
    Route::resource('/roles', 'RoleController', ['except' => ['destroy', 'show']]);

    Route::get('/profile', 'ProfileController@index')->name('profile');
    Route::put('/profile', 'ProfileController@update')->name('profile.update');

    Route::prefix('dictionaries')->group(function () {
        Route::resource('/app-contract-stages', 'AppContractStageController', ['except' => ['show']]);
        Route::resource('/ownership-types', 'OwnershipTypeController', ['except' => ['show']]);
        Route::resource('/positions', 'PositionController', ['except' => ['show']]);
        Route::resource('/activities', 'ActivityController', ['except' => ['show']]);
        Route::resource('/hosting-services', 'HostingServiceController', ['except' => ['show']]);
        Route::resource('/regions', 'RegionController', ['except' => ['show']]);
        Route::resource('/cities', 'CityController', ['except' => ['show']]);
        Route::resource('/payment-methods', 'PaymentMethodController', ['except' => ['show']]);
        Route::resource('/bitrix-editions', 'BitrixEditionController', ['except' => ['show']]);
        Route::resource('/bitrix-crm-editions', 'BitrixCRMEditionController', ['except' => ['show']]);
        Route::resource('/amo-crm-editions', 'AmoCRMEditionController', ['except' => ['show']]);
    });

//    Route::get('/reports/{type}', 'ReportController@index')->where('type', 'smm|seo|ca|adm')->name('reports.index');
//    Route::get('/reports/{report}/edit', 'ReportController@edit')->name('reports.edit');
//    Route::put('/reports/{report}/edit', 'ReportController@update')->name('reports.update');
//    Route::get('/reports/{report}/download-report', 'ReportController@downloadReport')->name('reports.download-report');
//    Route::get('/reports/{report}/download-act', 'ReportController@downloadAct')->name('reports.download-act');
//    Route::delete('/reports/{report}', 'ReportController@destroy')->name('reports.destroy');

    Route::get('/reports/generate', 'ReportController@generate')->name('reports.generate');

    Route::get('/contracts/{status?}', 'ContractController@index')->where('status', 'new|active|declined|completed|unsigned')->name('contracts.index');
    Route::get('/contracts/download/{status?}', 'ContractController@download')->where('status', 'new|active|declined|completed')->name('contracts.download');
    Route::match(['get', 'post'],'/contracts/correct/{contract}', 'ContractController@correct')
        ->name('contracts.correct');

    Route::post('/contracts/get-client-contracts', 'ContractController@getClientContracts')
        ->name('contracts.get-client-contracts');

    Route::resource('/contracts', 'ContractController', [
        'except' => ['show', 'index'],
        'names' => [
            'create' => 'contracts.create',
            'store' => 'contracts.store',
            'edit' => 'contracts.edit',
            'update' => 'contracts.update',

app/Role.php
<?php

namespace App;

use Laratrust\LaratrustRole;

class Role extends LaratrustRole
{
    //
}

app/Http/Controllers/RoleController.php
<?php

namespace App\Http\Controllers;

use App\Permission;
use App\Role;
use App\Http\Requests\StoreRole as StoreRoleRequest;
use Illuminate\Support\Facades\Session;

class RoleController extends Controller
{
    public function __construct()
    {
        $this->middleware('permission:read-acl', ['only' => ['index']]);
        $this->middleware('permission:create-acl', ['only' => ['create', 'store']]);
        $this->middleware('permission:update-acl', ['only' => ['edit', 'update']]);
    }

    public function index()
    {
        $roles = Role::all();

        return view('role.index', [
            'roles' => $roles
        ]);
    }

    public function create()
    {
        $permissions = Permission::all();

        $groupedPermissions = [];

        foreach ($permissions as $permission) {
            $groupedPermissions[$permission->group ?: __('Others')][] = $permission;
        }

        ksort($groupedPermissions);

        return view('role.create',[
            'groupedPermissions' => $groupedPermissions
        ]);
    }

    public function store(StoreRoleRequest $request)
    {
        $role = new Role();
        $role->name = $request->name;
        $role->display_name = $request->display_name;
        $role->description = $request->description;

        if ($role->save()) {
            Session::flash('success', __('Role has been saved successfully'));
        } else {
            Session::flash('danger', __('An error occurred'));
        }

        if ($request->permissions) {
            $role->syncPermissions($request->permissions);
        }

        return redirect()->route('roles.edit', ['id' => $role->id]);
    }

    public function edit($id)
    {
        $role = Role::where('id', $id)->with('permissions')->first();
        $permissions = Permission::all();

        $groupedPermissions = [];

        foreach ($permissions as $permission) {
            $groupedPermissions[$permission->group ?: __('Others')][] = $permission;
        }

        ksort($groupedPermissions);

        return view('role.edit',[
            'role' => $role,
            'groupedPermissions' => $groupedPermissions
        ]);
    }

    public function update(StoreRoleRequest $request, $id)
    {
        $role = Role::findOrFail($id);

        $role->display_name = $request->display_name;
        $role->description = $request->description;

        if ($role->save()) {
            Session::flash('success', __('Role has been updated successfully'));
        } else {
            Session::flash('danger', __('An error occurred'));
        }

        if ($request->permissions) {
            $role->syncPermissions($request->permissions);
        }

        return redirect()->route('roles.edit', ['id' => $role->id]);
    }
}

resources/views/role/partial/form.blade.php
<form method="post" action="@if (isset($role)){{ route('roles.update', $role->id) }}@else{{ route('roles.store') }}@endif" novalidate>
    <div class="row">
        <div class="col-lg-4 col-md-9">
            {{ csrf_field() }}
            @if (isset($role))
                {{ method_field('PUT') }}
                <input type="hidden" name="id" value="{{ $role->id }}">
            @endif
            <div class="form-group">
                <label>{{ __('Role Name') }}</label>
                <input type="text" name="display_name" class="form-control @if ($errors->has('display_name')) is-invalid @endif" value="{{ old('display_name') ?: (isset($role) ? $role->display_name : '') }}">
                @if ($errors->has('display_name'))
                    <div class="invalid-feedback">{{ $errors->first('display_name') }}</div>
                @endif
            </div>
            <div class="form-group">
                <label>{{ __('Slug') }}</label>
                <input type="text" name="name" class="form-control @if ($errors->has('name')) is-invalid @endif" value="{{ old('name') ?: (isset($role) ? $role->name : '') }}" @if (isset($role)) disabled @endif>

                @if ($errors->has('name'))
                    <div class="invalid-feedback">{{ $errors->first('name') }}</div>
                @endif
            </div>
            <div class="form-group">
                <label>{{ __('Description') }}</label>
                <input type="text" name="description" class="form-control @if ($errors->has('description')) is-invalid @endif" value="{{ old('description') ?: (isset($role) ? $role->description : '') }}">
                @if ($errors->has('description'))
                    <div class="invalid-feedback">{{ $errors->first('description') }}</div>
                @endif
            </div>
        </div>
    </div>

    <div class="h4 mb-2 mt-4">{{ __('Permissions') }}</div>
    <ul class="nav nav-tabs mb-4" id="myTab" role="tablist">
        @foreach(array_keys($groupedPermissions) as $key => $group)
            <li class="nav-item">
                <a class="nav-link @if (!$key) active @endif" data-toggle="tab" href="#tab{{ $key }}" role="tab" aria-selected="true">{{ $group }}</a>
            </li>
        @endforeach
    </ul>

    <div class="tab-content mb-4">
        @php($key = 0)
        @foreach($groupedPermissions as $group => $permissions)
            <div class="tab-pane fade @if (!$key) show active @endif" id="tab{{$key}}" role="tabpanel">
                @foreach ($permissions as $permission)
                    <div class="form-check">
                        <label class="form-check-label">
                            <input class="form-check-input" type="checkbox" name="permissions[]" value="{{ $permission->id }}" @if (old('permissions') && in_array($permission->id, old('permissions'))) checked @elseif (isset($role) && in_array($permission->id, $role->permissions->pluck('id')->toArray())) checked @endif>
                            {{ $permission->display_name }}
                        </label>
                    </div>
                @endforeach
            </div>
            @php(++$key)
        @endforeach
    </div>
    <button type="submit" class="btn btn-primary">{{ __('Submit') }}</button>
</form>