routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::get('/', 'SiteController@index');

Route::middleware(['auth'])->group(function () {
    Route::resource('/users', 'UserController', ['except' => ['show']]);

    Route::resource('/contacts', 'ContactController', ['except' => ['show']]);
    Route::get('/contacts/clients', 'ContactController@clients')->name('contacts.clients');
    Route::get('/contacts/suppliers', 'ContactController@suppliers')->name('contacts.suppliers');
    Route::get('/contacts/clients/download', 'ContactController@downloadClientsContacts')->name('contacts.clients.download');
    Route::get('/contacts/suppliers/download', 'ContactController@downloadSuppliersContacts')->name('contacts.suppliers.download');
    Route::delete('/contacts/{contact}/force-delete', 'ContactController@forceDelete')->name('contacts.force-delete');
    Route::get('/contacts/{contact}/restore', 'ContactController@restore')->name('contacts.restore');


    Route::get('/clients/{client}/contacts', 'ClientController@contacts')->name('clients.contacts');
    Route::get('/clients/download', 'ClientController@download')->name('clients.download');
    Route::delete('/clients/{client}/force-delete', 'ClientController@forceDelete')->name('clients.force-delete');
    Route::get('/clients/{client}/restore', 'ClientController@restore')->name('clients.restore');
    Route::resource('/clients', 'ClientController');

    Route::get('/suppliers/{supplier}/contacts', 'SupplierController@contacts')->name('suppliers.contacts');
    Route::get('/suppliers/download', 'SupplierController@download')->name('suppliers.download');
    Route::get('/suppliers/{supplier}/download-contract', 'SupplierController@downloadContract')->name('suppliers.contract.download');
    Route::delete('/suppliers/{supplier}/force-delete', 'SupplierController@forceDelete')->name('suppliers.force-delete');
    Route::get('/suppliers/{supplier}/restore', 'SupplierController@restore')->name('suppliers.restore');
    Route::resource('/suppliers', 'SupplierController');

    Route::get('/contracts/ca/{status?}', 'CAContractController@index')->where('status', 'active|declined|deleted')->name('contracts.ca.index');
    Route::get('/contracts/ca/create', 'CAContractController@create')->name('contracts.ca.create');
    Route::post('/contracts/ca/store', 'CAContractController@store')->name('contracts.ca.store');
    Route::get('/contracts/ca/{contract}/edit', 'CAContractController@edit')->name('contracts.ca.edit');
    Route::put('/contracts/ca/{contract}', 'CAContractController@update')->name('contracts.ca.update');
    Route::get('/contracts/ca/{contract}', 'CAContractController@show')->name('contracts.ca.show');
    Route::delete('/contracts/ca/{contract}', 'CAContractController@destroy')->name('contracts.ca.destroy');
    Route::delete('/contracts/ca/{contract}/force-delete', 'CAContractController@forceDelete')->name('contracts.ca.force-delete');
    Route::get('/contracts/ca/{contract}/restore', 'CAContractController@restore')->name('contracts.ca.restore');
    Route::get('/contracts/ca/{contract}/download', 'CAContractController@download')->name('contracts.ca.download');
    Route::post('/contracts/ca/{contract}/decline', 'CAContractController@decline')->name('contracts.ca.decline');
    Route::get('/contracts/ca/{contract}/activate', 'CAContractController@activate')->name('contracts.ca.activate');
    Route::get('/contracts/ca/{contract}/download-file/{file}', 'CAContractController@downloadFile')->name('contracts.ca.download-file');
    Route::get('/contracts/ca/{contract}/delete-file/{file}', 'CAContractController@deleteFile')->name('contracts.ca.delete-file');
    Route::get('/contracts/ca/{contract}/download-cancellation-letter', 'CAContractController@downloadCancellationLetter')->name('contracts.ca.download-cancellation-letter');
    Route::get('/contracts/ca/{contract}/download-cancellation-agreement', 'CAContractController@downloadCancellationAgreement')->name('contracts.ca.download-cancellation-agreement');

    Route::get('/contracts/smm/{status?}', 'SMMContractController@index')->where('status', 'active|declined')->name('contracts.smm.index');
    Route::get('/contracts/smm/create', 'SMMContractController@create')->name('contracts.smm.create');
    Route::post('/contracts/smm/store', 'SMMContractController@store')->name('contracts.smm.store');
    Route::get('/contracts/smm/{contract}/edit', 'SMMContractController@edit')->name('contracts.smm.edit');
    Route::get('/contracts/smm/{contract}', 'SMMContractController@show')->name('contracts.smm.show');
    Route::put('/contracts/smm/{contract}', 'SMMContractController@update')->name('contracts.smm.update');
    Route::delete('/contracts/smm/{contract}', 'SMMContractController@destroy')->name('contracts.smm.destroy');
    Route::delete('/contracts/smm/{contract}/force-delete', 'SMMContractController@forceDelete')->name('contracts.smm.force-delete');
    Route::get('/contracts/smm/{contract}/restore', 'SMMContractController@restore')->name('contracts.smm.restore');
    Route::get('/contracts/smm/{contract}/download', 'SMMContractController@download')->name('contracts.smm.download');
    Route::post('/contracts/smm/{contract}/decline', 'SMMContractController@decline')->name('contracts.smm.decline');
    Route::get('/contracts/smm/{contract}/activate', 'SMMContractController@activate')->name('contracts.smm.activate');
    Route::get('/contracts/smm/{contract}/download-file/{file}', 'SMMContractController@downloadFile')->name('contracts.smm.download-file');
    Route::get('/contracts/smm/{contract}/delete-file/{file}', 'SMMContractController@deleteFile')->name('contracts.smm.delete-file');
    Route::get('/contracts/smm/{contract}/download-cancellation-letter', 'SMMContractController@downloadCancellationLetter')->name('contracts.smm.download-cancellation-letter');
    Route::get('/contracts/smm/{contract}/download-cancellation-agreement', 'SMMContractController@downloadCancellationAgreement')->name('contracts.smm.download-cancellation-agreement');

    Route::get('/contracts/adm/{status?}', 'AdmContractController@index')->where('status', 'active|declined|deleted')->name('contracts.adm.index');
    Route::get('/contracts/adm/create', 'AdmContractController@create')->name('contracts.adm.create');
    Route::post('/contracts/adm/store', 'AdmContractController@store')->name('contracts.adm.store');
    Route::get('/contracts/adm/{contract}/edit', 'AdmContractController@edit')->name('contracts.adm.edit');
    Route::put('/contracts/adm/{contract}', 'AdmContractController@update')->name('contracts.adm.update');
    Route::get('/contracts/adm/{contract}', 'AdmContractController@show')->name('contracts.adm.show');
    Route::delete('/contracts/adm/{contract}', 'AdmContractController@destroy')->name('contracts.adm.destroy');
    Route::delete('/contracts/adm/{contract}/force-delete', 'AdmContractController@forceDelete')->name('contracts.adm.force-delete');
    Route::get('/contracts/adm/{contract}/restore', 'AdmContractController@restore')->name('contracts.adm.restore');
    Route::get('/contracts/adm/{contract}/download', 'AdmContractController@download')->name('contracts.adm.download');
    Route::post('/contracts/adm/{contract}/decline', 'AdmContractController@decline')->name('contracts.adm.decline');
    Route::get('/contracts/adm/{contract}/activate', 'AdmContractController@activate')->name('contracts.adm.activate');
    Route::get('/contracts/adm/{contract}/download-file/{file}', 'AdmContractController@downloadFile')->name('contracts.adm.download-file');
    Route::get('/contracts/adm/{contract}/delete-file/{file}', 'AdmContractController@deleteFile')->name('contracts.adm.delete-file');
    Route::get('/contracts/adm/{contract}/download-cancellation-letter', 'AdmContractController@downloadCancellationLetter')->name('contracts.adm.download-cancellation-letter');
    Route::get('/contracts/adm/{contract}/download-cancellation-agreement', 'AdmContractController@downloadCancellationAgreement')->name('contracts.adm.download-cancellation-agreement');
    Route::get('/contracts/adm/download/{status?}', 'AdmContractController@export')->where('status', 'active|declined|deleted')->name('contracts.adm.export');

    Route::get('/contracts/seo/{status?}', 'SeoContractController@index')->where('status', 'active|declined|deleted')->name('contracts.seo.index');
    Route::get('/contracts/seo/create', 'SeoContractController@create')->name('contracts.seo.create');
    Route::post('/contracts/seo/store', 'SeoContractController@store')->name('contracts.seo.store');
    Route::get('/contracts/seo/{contract}/edit', 'SeoContractController@edit')->name('contracts.seo.edit');
    Route::put('/contracts/seo/{contract}', 'SeoContractController@update')->name('contracts.seo.update');
    Route::get('/contracts/seo/{contract}', 'SeoContractController@show')->name('contracts.seo.show');
    Route::delete('/contracts/seo/{contract}', 'SeoContractController@destroy')->name('contracts.seo.destroy');
    Route::delete('/contracts/seo/{contract}/force-delete', 'SeoContractController@forceDelete')->name('contracts.seo.force-delete');
    Route::get('/contracts/seo/{contract}/restore', 'SeoContractController@restore')->name('contracts.seo.restore');
    Route::get('/contracts/seo/{contract}/download', 'SeoContractController@download')->name('contracts.seo.download');
    Route::post('/contracts/seo/{contract}/decline', 'SeoContractController@decline')->name('contracts.seo.decline');

app/Contact.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Contact extends Model
{
    use SoftDeletes;

    protected $fillable = [
        'contactable_id', 'contactable_type', 'name', 'email', 'phone', 'position_id'
    ];

    protected $dates = [
        'created_at',
        'updated_at',
        'deleted_at',
    ];

    public function contactable()
    {
        return $this->morphTo();
    }

    public function position()
    {
        return $this->belongsTo(Position::class);
    }
}

resources/views/contact/partial/form.blade.php
<form method="post" action="@if (isset($contact)){{ route('contacts.update', $contact->id) }}@else{{ route('contacts.store')}}@endif" novalidate>
    {{ csrf_field() }}
    @if (isset($contact))
        {{ method_field('PUT') }}
        <input type="hidden" name="id" value="{{ $contact->id }}">
    @endif

    @if (request('client_id'))
        <input type="hidden" name="client_id" value="{{ request('client_id') }}">
    @endif

    @if (request('supplier_id'))
        <input type="hidden" name="supplier_id" value="{{ request('supplier_id') }}">
    @endif

    @if (!isset($contact) && !request('client_id') && !request('supplier_id'))
        @if (request('contactable') == 'client')
            <div class="form-group">
                <label>{{ __('Client') }}</label>
                <select class="@if ($errors->has('client_id')) is-invalid @endif" name="client_id">
                    <option value="">{{ __('None') }}</option>
                    @foreach (App\Client::all() as $client)
                        <option value="{{ $client->id }}" @if (old('client_id') == $client->id) selected="selected" @elseif (isset($contact) && $contact->client->id == $client->id) selected="selected" @endif>{{ $client->getFullName() }}</option>
                    @endforeach
                </select>
                @if ($errors->has('client_id'))
                    <div class="invalid-feedback">{{ $errors->first('client_id') }}</div>
                @endif
            </div>
        @endif

        @if (request('contactable') == 'supplier')
            <div class="form-group">
                <label>{{ __('Supplier') }}</label>
                <select class="@if ($errors->has('client_id')) is-invalid @endif" name="supplier_id">
                    <option value="">{{ __('None') }}</option>
                    @foreach (App\Supplier::all() as $supplier)
                        <option value="{{ $supplier->id }}" @if (old('supplier_id') == $supplier->id) selected="selected" @elseif (isset($contact) && $contact->client->id == $supplier->id) selected="selected" @endif>{{ $supplier->getFullName() }}</option>
                    @endforeach
                </select>
                @if ($errors->has('supplier_id'))
                    <div class="invalid-feedback">{{ $errors->first('supplier_id') }}</div>
                @endif
            </div>
        @endif
    @endif
    <div class="form-group">
        <label>{{ __('Full Name') }}</label>
        <input type="text" name="name" class="form-control @if ($errors->has('name')) is-invalid @endif" value="{{ old('name') ?: (isset($contact) ? $contact->name : '')}}">
        @if ($errors->has('name'))
            <div class="invalid-feedback">{{ $errors->first('name') }}</div>
        @endif
    </div>
    <div class="form-group">
        <label>{{ __('Email') }}</label>
        <input type="email" name="email" class="form-control @if ($errors->has('email')) is-invalid @endif"  value="{{ old('email') ?: (isset($contact) ? $contact->email : '')}}">
        @if ($errors->has('email'))
            <div class="invalid-feedback">{{ $errors->first('email') }}</div>
        @endif
    </div>
    <div class="form-group">
        <label>{{ __('Phone') }}</label>
        <input type="text" name="phone" class="form-control @if ($errors->has('phone')) is-invalid @endif" value="{{ old('phone') ?: (isset($contact) ? $contact->phone : '')}}">
        @if ($errors->has('phone'))
            <div class="invalid-feedback">{{ $errors->first('phone') }}</div>
        @endif
    </div>
    <div class="form-group">
        <label>{{ __('Position') }}</label>
        <select class="@if ($errors->has('position_id')) is-invalid @endif" name="position_id">
            <option value="">{{ __('None') }}</option>
            @foreach (App\Position::where('inhouse', 0)->get() as $position)
                <option value="{{ $position->id }}" @if (old('position_id') == $position->id) selected="selected" @elseif (isset($contact) && $contact->position && $contact->position->id == $position->id) selected="selected" @endif>{{ $position->name }}</option>
            @endforeach
        </select>
        @if ($errors->has('position_id'))
            <div class="invalid-feedback">{{ $errors->first('position_id') }}</div>
        @endif
    </div>
    <button type="submit" class="btn btn-primary">{{ __('Submit') }}</button>
</form>