routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::get('/', 'SiteController@index');

Route::middleware(['auth'])->group(function () {
    Route::resource('/users', 'UserController', ['except' => ['show']]);

    Route::resource('/contacts', 'ContactController', ['except' => ['show']]);
    Route::get('/contacts/clients', 'ContactController@clients')->name('contacts.clients');
    Route::get('/contacts/suppliers', 'ContactController@suppliers')->name('contacts.suppliers');
    Route::get('/contacts/clients/download', 'ContactController@downloadClientsContacts')->name('contacts.clients.download');
    Route::get('/contacts/suppliers/download', 'ContactController@downloadSuppliersContacts')->name('contacts.suppliers.download');
    Route::delete('/contacts/{contact}/force-delete', 'ContactController@forceDelete')->name('contacts.force-delete');
    Route::get('/contacts/{contact}/restore', 'ContactController@restore')->name('contacts.restore');


    Route::get('/clients/{client}/contacts', 'ClientController@contacts')->name('clients.contacts');
    Route::get('/clients/download', 'ClientController@download')->name('clients.download');
    Route::delete('/clients/{client}/force-delete', 'ClientController@forceDelete')->name('clients.force-delete');
    Route::get('/clients/{client}/restore', 'ClientController@restore')->name('clients.restore');
    Route::resource('/clients', 'ClientController');

    Route::get('/suppliers/{supplier}/contacts', 'SupplierController@contacts')->name('suppliers.contacts');
    Route::get('/suppliers/download', 'SupplierController@download')->name('suppliers.download');
    Route::get('/suppliers/{supplier}/download-contract', 'SupplierController@downloadContract')->name('suppliers.contract.download');
    Route::delete('/suppliers/{supplier}/force-delete', 'SupplierController@forceDelete')->name('suppliers.force-delete');
    Route::get('/suppliers/{supplier}/restore', 'SupplierController@restore')->name('suppliers.restore');
    Route::resource('/suppliers', 'SupplierController');

    Route::get('/contracts/ca/{status?}', 'CAContractController@index')->where('status', 'active|declined|deleted')->name('contracts.ca.index');
    Route::get('/contracts/ca/create', 'CAContractController@create')->name('contracts.ca.create');
    Route::post('/contracts/ca/store', 'CAContractController@store')->name('contracts.ca.store');
    Route::get('/contracts/ca/{contract}/edit', 'CAContractController@edit')->name('contracts.ca.edit');
    Route::put('/contracts/ca/{contract}', 'CAContractController@update')->name('contracts.ca.update');
    Route::get('/contracts/ca/{contract}', 'CAContractController@show')->name('contracts.ca.show');
    Route::delete('/contracts/ca/{contract}', 'CAContractController@destroy')->name('contracts.ca.destroy');
    Route::delete('/contracts/ca/{contract}/force-delete', 'CAContractController@forceDelete')->name('contracts.ca.force-delete');
    Route::get('/contracts/ca/{contract}/restore', 'CAContractController@restore')->name('contracts.ca.restore');
    Route::get('/contracts/ca/{contract}/download', 'CAContractController@download')->name('contracts.ca.download');
    Route::post('/contracts/ca/{contract}/decline', 'CAContractController@decline')->name('contracts.ca.decline');
    Route::get('/contracts/ca/{contract}/activate', 'CAContractController@activate')->name('contracts.ca.activate');
    Route::get('/contracts/ca/{contract}/download-file/{file}', 'CAContractController@downloadFile')->name('contracts.ca.download-file');
    Route::get('/contracts/ca/{contract}/delete-file/{file}', 'CAContractController@deleteFile')->name('contracts.ca.delete-file');
    Route::get('/contracts/ca/{contract}/download-cancellation-letter', 'CAContractController@downloadCancellationLetter')->name('contracts.ca.download-cancellation-letter');
    Route::get('/contracts/ca/{contract}/download-cancellation-agreement', 'CAContractController@downloadCancellationAgreement')->name('contracts.ca.download-cancellation-agreement');

    Route::get('/contracts/smm/{status?}', 'SMMContractController@index')->where('status', 'active|declined')->name('contracts.smm.index');
    Route::get('/contracts/smm/create', 'SMMContractController@create')->name('contracts.smm.create');
    Route::post('/contracts/smm/store', 'SMMContractController@store')->name('contracts.smm.store');
    Route::get('/contracts/smm/{contract}/edit', 'SMMContractController@edit')->name('contracts.smm.edit');
    Route::get('/contracts/smm/{contract}', 'SMMContractController@show')->name('contracts.smm.show');
    Route::put('/contracts/smm/{contract}', 'SMMContractController@update')->name('contracts.smm.update');
    Route::delete('/contracts/smm/{contract}', 'SMMContractController@destroy')->name('contracts.smm.destroy');
    Route::delete('/contracts/smm/{contract}/force-delete', 'SMMContractController@forceDelete')->name('contracts.smm.force-delete');
    Route::get('/contracts/smm/{contract}/restore', 'SMMContractController@restore')->name('contracts.smm.restore');
    Route::get('/contracts/smm/{contract}/download', 'SMMContractController@download')->name('contracts.smm.download');
    Route::post('/contracts/smm/{contract}/decline', 'SMMContractController@decline')->name('contracts.smm.decline');
    Route::get('/contracts/smm/{contract}/activate', 'SMMContractController@activate')->name('contracts.smm.activate');
    Route::get('/contracts/smm/{contract}/download-file/{file}', 'SMMContractController@downloadFile')->name('contracts.smm.download-file');
    Route::get('/contracts/smm/{contract}/delete-file/{file}', 'SMMContractController@deleteFile')->name('contracts.smm.delete-file');
    Route::get('/contracts/smm/{contract}/download-cancellation-letter', 'SMMContractController@downloadCancellationLetter')->name('contracts.smm.download-cancellation-letter');
    Route::get('/contracts/smm/{contract}/download-cancellation-agreement', 'SMMContractController@downloadCancellationAgreement')->name('contracts.smm.download-cancellation-agreement');

    Route::get('/contracts/adm/{status?}', 'AdmContractController@index')->where('status', 'active|declined|deleted')->name('contracts.adm.index');
    Route::get('/contracts/adm/create', 'AdmContractController@create')->name('contracts.adm.create');
    Route::post('/contracts/adm/store', 'AdmContractController@store')->name('contracts.adm.store');
    Route::get('/contracts/adm/{contract}/edit', 'AdmContractController@edit')->name('contracts.adm.edit');
    Route::put('/contracts/adm/{contract}', 'AdmContractController@update')->name('contracts.adm.update');
    Route::get('/contracts/adm/{contract}', 'AdmContractController@show')->name('contracts.adm.show');
    Route::delete('/contracts/adm/{contract}', 'AdmContractController@destroy')->name('contracts.adm.destroy');
    Route::delete('/contracts/adm/{contract}/force-delete', 'AdmContractController@forceDelete')->name('contracts.adm.force-delete');
    Route::get('/contracts/adm/{contract}/restore', 'AdmContractController@restore')->name('contracts.adm.restore');
    Route::get('/contracts/adm/{contract}/download', 'AdmContractController@download')->name('contracts.adm.download');
    Route::post('/contracts/adm/{contract}/decline', 'AdmContractController@decline')->name('contracts.adm.decline');
    Route::get('/contracts/adm/{contract}/activate', 'AdmContractController@activate')->name('contracts.adm.activate');
    Route::get('/contracts/adm/{contract}/download-file/{file}', 'AdmContractController@downloadFile')->name('contracts.adm.download-file');
    Route::get('/contracts/adm/{contract}/delete-file/{file}', 'AdmContractController@deleteFile')->name('contracts.adm.delete-file');
    Route::get('/contracts/adm/{contract}/download-cancellation-letter', 'AdmContractController@downloadCancellationLetter')->name('contracts.adm.download-cancellation-letter');
    Route::get('/contracts/adm/{contract}/download-cancellation-agreement', 'AdmContractController@downloadCancellationAgreement')->name('contracts.adm.download-cancellation-agreement');
    Route::get('/contracts/adm/download/{status?}', 'AdmContractController@export')->where('status', 'active|declined|deleted')->name('contracts.adm.export');

    Route::get('/contracts/seo/{status?}', 'SeoContractController@index')->where('status', 'active|declined|deleted')->name('contracts.seo.index');
    Route::get('/contracts/seo/create', 'SeoContractController@create')->name('contracts.seo.create');
    Route::post('/contracts/seo/store', 'SeoContractController@store')->name('contracts.seo.store');
    Route::get('/contracts/seo/{contract}/edit', 'SeoContractController@edit')->name('contracts.seo.edit');
    Route::put('/contracts/seo/{contract}', 'SeoContractController@update')->name('contracts.seo.update');
    Route::get('/contracts/seo/{contract}', 'SeoContractController@show')->name('contracts.seo.show');
    Route::delete('/contracts/seo/{contract}', 'SeoContractController@destroy')->name('contracts.seo.destroy');
    Route::delete('/contracts/seo/{contract}/force-delete', 'SeoContractController@forceDelete')->name('contracts.seo.force-delete');
    Route::get('/contracts/seo/{contract}/restore', 'SeoContractController@restore')->name('contracts.seo.restore');
    Route::get('/contracts/seo/{contract}/download', 'SeoContractController@download')->name('contracts.seo.download');
    Route::post('/contracts/seo/{contract}/decline', 'SeoContractController@decline')->name('contracts.seo.decline');

app/Http/Controllers/SupplierController.php
<?php

namespace App\Http\Controllers;

use App\ActualAddress;
use App\LegalAddress;
use App\Supplier;
use App\Http\Requests\StoreSupplier as StoreSupplierRequest;
use App\SupplierContract;
use Illuminate\Support\Facades\Input;
use Illuminate\Support\Facades\Session;;
use Illuminate\Support\Facades\Storage;
use Maatwebsite\Excel\Facades\Excel;
use Illuminate\Http\Request;

class SupplierController extends Controller
{
    public function __construct()
    {
        $this->middleware('permission:read-suppliers', ['only' => ['index']]);
        $this->middleware('permission:create-suppliers', ['only' => ['create', 'store']]);
        $this->middleware('permission:update-suppliers', ['only' => ['edit', 'update']]);
        $this->middleware('permission:soft-delete-suppliers', ['only' => ['destroy']]);
        $this->middleware('permission:restore-suppliers', ['only' => ['restore']]);
        $this->middleware('permission:delete-suppliers', ['only' => ['forceDelete']]);
        $this->middleware('permission:export-suppliers', ['only' => ['download']]);
    }

    public function index(Request $request)
    {
        if ($request->removed == 1) {
            $query = Supplier::onlyTrashed();
        } else {
            $query = Supplier::select();
        }

        if ($request->legal_name) {
            $query->where('legal_name', $request->legal_name);
        }

        if ($request->brand) {
            $query->where('brand', $request->brand);
        }

        if ($request->site) {
            $query->where('site', 'like', '%' . $request->site . '%');
        }

        if ($request->activity_id) {
            $query->where('activity_id', $request->activity_id);
        }
        
        return view('supplier.index', [
            'suppliers' =>  $query->paginate(20)->appends(Input::except('page')),
        ]);
    }

    public function show(Supplier $supplier)
    {
        return view('supplier.show', [
            'supplier' => $supplier
        ]);
    }

    public function create()
    {
        return view('supplier.create');
    }

    public function store(StoreSupplierRequest $request)
    {
        $supplier = new Supplier($request->all());

        if ($supplier->save()) {
            if ($request->hasFile('contract_scan') && $request->file('contract_scan')->isValid()) {
                $contract = new SupplierContract();
                $contract->contract_scan = $request->contract_scan->store('files', 'public');
                $contract->number = $request->contract_number;

                $contract->supplier()->associate($supplier);
                $contract->save();
            }

            $actualAddress = $supplier->actualAddress ?: new ActualAddress();
            $actualAddress->city_id = $request->actual_address['city_id'];
            $actualAddress->full_address = $request->actual_address['full_address'];
            $actualAddress->agent_id = $supplier->id;
            $actualAddress->agent_type = 'supplier';
            $actualAddress->save();

            $legalAddress = $supplier->legalAddress ?: new LegalAddress();
            $legalAddress->city_id = $request->legal_address['city_id'];
            $legalAddress->full_address = $request->legal_address['full_address'];
            $legalAddress->agent_id = $supplier->id;
            $legalAddress->agent_type = 'supplier';
            $legalAddress->save();

            Session::flash('success', __('Supplier has been saved successfully'));
        } else {
            Session::flash('danger', __('An error occurred'));
        }

        return redirect()->route('suppliers.edit', ['id' => $supplier->id]);
    }

    public function edit(Supplier $supplier)
    {
        return view('supplier.edit', [
            'supplier' => $supplier
        ]);
    }

    public function update(StoreSupplierRequest $request, $id)
    {
        $supplier = Supplier::findOrFail($id);
        $supplier->fill($request->all());

        if ($supplier->save()) {
            if ($request->hasFile('contract_scan') && $request->file('contract_scan')->isValid()) {
                if ($supplier->contract->contract_scan) {
                    Storage::disk('public')->delete($supplier->contract->contract_scan);
                }

                $supplier->contract->contract_scan = $request->contract_scan->store('files', 'public');
                $supplier->contract->number = $request->contract_number;

                $supplier->contract->save();
            }

            $actualAddress = $supplier->actualAddress ?: new ActualAddress();
            $actualAddress->city_id = $request->actual_address['city_id'];
            $actualAddress->full_address = $request->actual_address['full_address'];
            $actualAddress->agent_id = $supplier->id;
            $actualAddress->agent_type = 'supplier';
            $actualAddress->save();

            $legalAddress = $supplier->legalAddress ?: new LegalAddress();
            $legalAddress->city_id = $request->legal_address['city_id'];
            $legalAddress->full_address = $request->legal_address['full_address'];
            $legalAddress->agent_id = $supplier->id;
            $legalAddress->agent_type = 'supplier';
            $legalAddress->save();

            Session::flash('success', __('Supplier has been updated successfully'));
        } else {
            Session::flash('danger', __('An error occurred'));
        }

        return redirect()->route('suppliers.edit', ['id' => $supplier->id]);
    }

    public function destroy($id)
    {
        $supplier = Supplier::findOrFail($id);
        $supplier->delete();

        return redirect()->route('suppliers.index');
    }

    public function forceDelete($id)
    {
        $supplier = Supplier::withTrashed()->where('id', $id)->first();
        $supplier->forceDelete();

        return redirect()->back();
    }

    public function restore($id)
    {
        $supplier = Supplier::withTrashed()->where('id', $id)->first();
        $supplier->restore();

        return redirect()->back();
    }

    public function contacts(Supplier $supplier)
    {
        return view('supplier.contacts', [
            'supplier' => $supplier,
            'contacts' => $supplier->contacts
        ]);
    }

    public function download()
    {
        return Excel::create(__('Suppliers'), function($excel) {
            $excel->sheet('Excel sheet', function($sheet) {
                $sheet->setCellValue('A1', __('Legal Name'));
                $sheet->setCellValue('B1', __('Brand'));
                $sheet->setCellValue('C1', __('Kind of Activity'));
                $sheet->setCellValue('D1', __('Site'));

                $suppliers = Supplier::all();

                $rowNumber = 2;

                foreach ($suppliers as $supplier) {
                    $sheet->setCellValue('A' . $rowNumber, $supplier->legal_name . ', ' . $supplier->ownershipType->name);
                    $sheet->setCellValue('B' . $rowNumber, $supplier->brand);
                    $sheet->setCellValue('C' . $rowNumber, $supplier->activity ? $supplier->activity->name : '');
                    $sheet->setCellValue('D' . $rowNumber, $supplier->site);

                    $rowNumber++;
                }

            });
        })->export('xlsx');
    }

    public function downloadContract(Supplier $supplier)
    {
        return response()->download(storage_path('app/public/' . $supplier->contract->contract_scan));
    }
}

resources/views/supplier/contacts.blade.php
@extends('layouts.app')

@section('content')
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="{{ route('suppliers.index') }}">{{ __('Suppliers') }}</a></li>
        <li class="breadcrumb-item">{{ $supplier->getFullName() }}</li>
    </ol>
    <h3 class="page-header">{{ __('Contacts') }}</h3>
    <p>
        <a class="btn btn-secondary" href="{{ route('contacts.create', ['supplier_id' => $supplier->id]) }}">{{ __('Create Contact') }}</a>
    </p>
    <table class="table table-striped table-responsive">
        <thead>
        <tr>
            <th>#</th>
            <th>{{ __('Full Name') }}</th>
            <th>{{ __('E-mail') }}</th>
            <th>{{ __('Phone') }}</th>
            <th>{{ __('Position') }}</th>
            <th>{{ __('Action') }}</th>
        </tr>
        </thead>
        <tbody>
        @forelse ($contacts as $contact)
            <tr>
                <td>{{ $contact->id }}</td>
                <td>{{ $contact->name }}</td>
                <td>{{ $contact->email }}</td>
                <td>{{ $contact->phone }}</td>
                <td>{{ $contact->position ? $contact->position->name : '' }}</td>
                <td class="text-right">
                    <div class="btn-group btn-group-sm" role="group">
                        @permission('update-contacts')
                            <a class="btn btn-secondary" title="Edit" href="{{ route('contacts.edit', ['id' => $contact->id]) }}"><i class="fa fa-pencil" aria-hidden="true"></i></a>
                        @endpermission
                        @permission('delete-contacts')
                            <button class="btn btn-danger" title="Delete" data-href="{{ route('contacts.destroy', ['id' => $contact->id]) }}" data-toggle="modal" data-target="#confirm-delete"><i class="fa fa-trash" aria-hidden="true"></i></button>
                        @endpermission
                    </div>
                </td>
            </tr>
        @empty
            <tr>
                <td colspan="6">{{ __('Nothing found') }}</td>
            </tr>
        @endforelse
        </tbody>
    </table>

    @include('partial.confirm-delete')
@endsection

resources/views/supplier/create.blade.php
@extends('layouts.app')

@section('content')
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="{{ route('suppliers.index') }}">{{ __('Suppliers') }}</a></li>
    </ol>
    <h3 class="page-header">{{ __('Create Supplier') }}</h3>
    <div class="row">
        <div class="col-lg-4 col-md-9">
            @include('supplier.partial.form')
        </div>
    </div>
@endsection

resources/views/supplier/edit.blade.php
@extends('layouts.app')

@section('content')
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="{{ route('suppliers.index') }}">{{ __('Suppliers') }}</a></li>
    </ol>
    <h3 class="page-header">{{ __('Edit Supplier') }}</h3>
    <div class="row">
        <div class="col-lg-4 col-md-9">
            @include('supplier.partial.form', ['supplier' => $supplier])
        </div>
    </div>
@endsection

resources/views/supplier/index.blade.php
@extends('layouts.app')

@section('content')
    <h3 class="page-header">{{ __('Suppliers') }}</h3>
    <p>
        @permission('create-suppliers')
            <a class="btn btn-secondary" href="{{ route('suppliers.create') }}">{{ __('Create Supplier') }}</a>
        @endpermission

        @permission('export-suppliers')
            <a class="btn btn-primary" href="{{ route('suppliers.download') }}"><i class="fa fa-file-excel-o"></i>&nbsp;{{ __('To Excel') }}</a>
        @endpermission
    </p>
    <form action="" method="get" class="mb-3">
        <div class="form-row">
            <div class="form-group col-lg-2">
                <select name="legal_name">
                    <option value="">{{ __('Supplier') }}</option>
                    @foreach (App\Supplier::all() as $supplier)
                        <option value="{{ $supplier->legal_name }}" @if (request('legal_name') == $supplier->legal_name) selected @endif>{{ $supplier->getFullName() }}</option>
                    @endforeach
                </select>
            </div>
            <div class="form-group col-lg-2">
                <select name="brand">
                    <option value="">{{ __('Brand') }}</option>
                    @foreach (App\Supplier::all() as $supplier)
                        <option value="{{ $supplier->brand }}" @if (request('brand') == $supplier->brand) selected @endif>{{ $supplier->brand }}</option>
                    @endforeach
                </select>
            </div>
            <div class="form-group col-lg-2">
                <input class="form-control" name="site" placeholder="{{ __('Site') }}" value="{{ Request::get('site') }}">
            </div>
            <div class="form-group col-lg-2">
                <select name="activity_id">
                    <option value="">Вид деятельности</option>
                    @foreach (\App\Activity::all() as $activity)
                        <option value="{{ $activity->id }}" @if (request('activity_id') == $activity->id) selected @endif>{{ $activity->name }}</option>
                    @endforeach
                </select>
            </div>
            <div class="form-group col-lg-2">
                <div class="form-check mt-2">
                    <input class="form-check-input ml-0" type="checkbox" id="checkRemoved" name="removed" value="1" @if (request('removed') == '1') checked @endif>
                    <label class="form-check-label" for="checkRemoved">Архив</label>
                </div>
            </div>
            <div class="form-group col-lg-2">
                <button type="submit" class="btn btn-primary">{{ __('Search') }}</button>
            </div>
        </div>
    </form>
    <table class="table table-striped table-responsive">
        <thead>
        <tr>
            <th>#</th>
            <th>{{ __('Legal Name') }}</th>
            <th>{{ __('Brand') }}</th>
            <th>{{ __('Kind of Activity') }}</th>
            <th>{{ __('Site') }}</th>
            <th>{{ __('Contract Scan') }}</th>
            @permission('read-contacts')
                <th>{{ __('Contacts') }}</th>
            @endpermission
            <th>{{ __('Action') }}</th>
        </tr>
        </thead>
        <tbody>
            @forelse ($suppliers as $supplier)
                <tr>
                    <td>{{ $supplier->id }}</td>
                    <td><a href="{{ route('suppliers.show', ['id' => $supplier->id]) }}">{{ $supplier->getFullName() }}</a></td>
                    <td>{{ $supplier->brand }}</td>
                    <td>{{ $supplier->activity ? $supplier->activity->name : ''}}</td>
                    <td><a href="{{ $supplier->site }}" target="_blank">{{ $supplier->site }}</a></td>
                    <td><a href="{{ route('suppliers.contract.download', ['supplier' => $supplier->id]) }}">{{ __('Download') }}</a></td>
                    @permission('read-contacts')
                        <td><a href="{{ route('suppliers.contacts', ['id' => $supplier->id]) }}">{{ __('View Contacts') }}</a></td>
                    @endpermission
                    <td class="text-right">
                        <div class="btn-group btn-group-sm" role="group">
                            @if ($supplier->trashed())
                                @permission('restore-suppliers')
                                    <a class="btn btn-success" title="Восстановить" href="{{ route('suppliers.restore', ['id' => $supplier->id]) }}"><i class="fa fa-history" aria-hidden="true"></i></a>
                                @endpermission
                                @permission('delete-suppliers')
                                    <button class="btn btn-danger" title="{{ __('Delete') }}" data-href="{{ route('suppliers.force-delete', ['id' => $supplier->id]) }}" data-toggle="modal" data-target="#confirm-force-delete"><i class="fa fa-trash" aria-hidden="true"></i></button>
                                @endpermission
                            @else
                                @permission('update-suppliers')
                                    <a class="btn btn-secondary" title="Редактировать" href="{{ route('suppliers.edit', ['id' => $supplier->id]) }}"><i class="fa fa-pencil" aria-hidden="true"></i></a>
                                @endpermission
                                @permission('soft-delete-suppliers')
                                    <button class="btn btn-danger" title="Поместить в архив" data-href="{{ route('suppliers.destroy', ['id' => $supplier->id]) }}" data-toggle="modal" data-target="#confirm-delete"><i class="fa fa-trash" aria-hidden="true"></i></button>
                                @endpermission
                            @endif
                        </div>
                    </td>
                </tr>
            @empty
                <tr>
                    <td colspan="8">{{ __('Nothing found') }}</td>
                </tr>
            @endforelse
        </tbody>
    </table>
    {{ $suppliers->links('vendor.pagination.bootstrap-4') }}

    @include('partial.confirm-delete')
    @include('partial.confirm-force-delete')
@endsection

resources/views/supplier/show.blade.php
@extends('layouts.app')

@section('content')
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="{{ route('suppliers.index') }}">{{ __('Suppliers') }}</a></li>
    </ol>
    <h3 class="page-header">{{ __('Supplier') }}</h3>
    <div class="row">
        <div class="col-lg-4 col-md-9">
            <table class="table">
                <tr>
                    <td><strong>{{ __('Legal Name') }}</strong></td>
                    <td>{{ $supplier->legal_name }}, {{ $supplier->ownershipType->name }}</td>
                </tr>
                <tr>
                    <td><strong>{{ __('Brand') }}</strong></td>
                    <td>{{ $supplier->brand }}</td>
                </tr>
                <tr>
                    <td><strong>{{ __('Kind of Activity') }}</strong></td>
                    <td>{{ $supplier->activity ? $supplier->activity->name : '' }}</td>
                </tr>
                <tr>
                    <td><strong>{{ __('Site') }}</strong></td>
                    <td><a href="{{ $supplier->site }}" target="_blank">{{ $supplier->site }}</a></td>
                </tr>
                <tr>
                    <td><strong>{{ __('Actual Address') }}</strong></td>
                    <td>{{ $supplier->actualAddress ? $supplier->actualAddress->city->name . ', ' . $supplier->actualAddress->full_address : '' }}</td>
                </tr>
                <tr>
                    <td><strong>{{ __('Legal Address') }}</strong></td>
                    <td>{{ $supplier->legalAddress ? $supplier->legalAddress->city->name . ', ' . $supplier->legalAddress->full_address : '' }}</td>
                </tr>
            </table>
        </div>
    </div>
@endsection